// <auto-generated />
using System;
using FantasyFun.DataMigrator.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyFun.DataMigrator.Migrations
{
    [DbContext(typeof(SqlFootballDbContext))]
    [Migration("20221010203339_SupportNullableTeams")]
    partial class SupportNullableTeams
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.League", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ApiId")
                        .HasColumnType("int")
                        .HasColumnName("player_api_id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<int>("FifaApiId")
                        .HasColumnType("int")
                        .HasColumnName("player_fifa_api_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("player_name");

                    b.HasKey("Id");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Player_Attribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ApiId")
                        .HasColumnType("int")
                        .HasColumnName("player_api_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("FifaApiId")
                        .HasColumnType("int")
                        .HasColumnName("player_fifa_api_id");

                    b.Property<long>("OverallRating")
                        .HasColumnType("bigint")
                        .HasColumnName("overall_rating");

                    b.HasKey("Id");

                    b.HasIndex("ApiId");

                    b.ToTable("Player_Attributes", (string)null);
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_api_id");

                    b.Property<long?>("FifaApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_fifa_api_id");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("team_long_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("team_short_name");

                    b.HasKey("Id");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.League", b =>
                {
                    b.HasOne("FantasyFun.DataMigrator.Models.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Player_Attribute", b =>
                {
                    b.HasOne("FantasyFun.DataMigrator.Models.Player", "Player")
                        .WithMany("Players")
                        .HasForeignKey("ApiId")
                        .HasPrincipalKey("ApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Country", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("FantasyFun.DataMigrator.Models.Player", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
